version: '3.8'
services:
  ss-postgres:
    env_file:
      - .env
    image: postgres:${POSTGRES_VERSION}
    container_name: ${SERVICE_NAME}-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=${TIMEZONE}
    # command: --default_authentication_plugin=mysql_native_password
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${POSTGRES_DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data

    ports:
      - '${POSTGRES_MAPPING_DB_PORT}:5432'
