version: '3.8'
services:
  pr-mysql:
    env_file:
      - .env
    image: mysql:${MYSQL_VERSION}
    container_name: ${SERVICE_NAME}-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    command: --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${MYSQL_DATA_SAVE_PATH}/mysql:/var/lib/mysql

    ports:
      - '${MYSQL_MAPPING_DB_PORT}:3306'
