version: '3.8'
services:
  ss-postgres:
    env_file:
      - .env
    image: postgres:${POSTGRES_VERSION}
    container_name: ${SERVICE_NAME}-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_MAPPING_DB_PORT}:${POSTGRES_PORT}'
